// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSHfRRBOpbakBRNtd6u3zcfTwAe9Vl1dM',
    appId: '1:389945035501:web:75de961ae6b257b6e41ae4',
    messagingSenderId: '389945035501',
    projectId: 'monkey-chat-e49cf',
    authDomain: 'monkey-chat-e49cf.firebaseapp.com',
    storageBucket: 'monkey-chat-e49cf.appspot.com',
    measurementId: 'G-HSP2QV6T5V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa9nseG31zpgoqj7jF0j_KvtF-CjbUZtc',
    appId: '1:389945035501:android:183cc8797ccd0f9de41ae4',
    messagingSenderId: '389945035501',
    projectId: 'monkey-chat-e49cf',
    storageBucket: 'monkey-chat-e49cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvTjKIVrI-66JRbyctdCcnudNGtY_x7-8',
    appId: '1:389945035501:ios:edab9afb39d842f9e41ae4',
    messagingSenderId: '389945035501',
    projectId: 'monkey-chat-e49cf',
    storageBucket: 'monkey-chat-e49cf.appspot.com',
    iosBundleId: 'com.example.chatMessager',
  );
}
